ALTER TABLE public.sp_results ADD COLUMN IF NOT EXISTS source TEXT, ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMPTZ;
ALTER TABLE public.federal_results ADD COLUMN IF NOT EXISTS source TEXT, ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMPTZ;
ALTER TABLE public.capital_results ADD COLUMN IF NOT EXISTS source TEXT, ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMPTZ;